import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root=process.cwd();
const read=(file)=>fs.readFileSync(path.join(root,file),"utf8");
const routes=["terms","privacy","sms-terms","communications-preferences","privacy-choices","cookies","refund-cancellation","service-fulfillment","provider-standards","how-it-works","accessibility","contact"];
for(const route of routes) assert.ok(fs.existsSync(path.join(root,"app",route,"page.tsx")),`missing /${route}`);
const form=read("components/RequestForm.tsx");
for(const field of ["firstName","lastName","email","phone","service","address","city","state","postalCode","preferredDate","preferredTime","message","providerAuthorization","smsConsent","termsAcknowledgement"]) assert.match(form,new RegExp(`name=[\\"']${field}[\\"']`),`missing field ${field}`);
assert.match(form,/type="checkbox" value="yes"/); assert.doesNotMatch(form,/defaultChecked/);
assert.match(read("lib/compliance.ts"),/By checking this optional box, I agree to receive recurring service-related SMS messages from Booked4Seasons, operated by Codestra LLC, at the mobile number provided, including messages concerning my service request, appointment coordination, provider updates, and customer support\. Message frequency varies\. Message and data rates may apply\. Reply HELP for help or STOP to opt out\. Consent is not a condition of requesting or purchasing services\./);
assert.match(read("app/privacy/page.tsx"),/Mobile phone numbers, SMS opt-in data, and messaging consent will not be shared, sold, rented, or transferred to third parties or affiliates for marketing or promotional purposes\./);
const smsTerms=read("app/sms-terms/page.tsx");
for(const requirement of [/Booked4Seasons messaging program/,/Message frequency varies/,/Message and data rates may apply/,/Reply STOP/,/Reply HELP/,/Carriers are not liable for delayed or undelivered messages/,/href="\/privacy"/]) assert.match(smsTerms,requirement);
assert.match(form,/not yet a confirmed appointment/i); assert.match(form,/No online payment is required or collected/i);
const chat=read("components/LeadConnectorChat.tsx");
assert.match(chat,/src="https:\/\/widgets\.leadconnectorhq\.com\/loader\.js"/);
assert.match(chat,/data-resources-url="https:\/\/widgets\.leadconnectorhq\.com\/chat-widget\/loader\.js"/);
assert.match(chat,/data-widget-id="6a7ca95093aa928cd28c82f8"/);
assert.match(chat,/data-source="WEB_USER"/);
const all=fs.readdirSync(path.join(root,"app"),{recursive:true}).filter(x=>String(x).endsWith(".tsx")).map(x=>read(path.join("app",String(x)))).join("\n");
for(const phrase of [/buying leads/i,/selling leads/i,/lead resale/i,/affiliate lead program/i,/payment webhook/i,/credit.card field/i]) assert.doesNotMatch(all,phrase);
const repositoryText=[".env.example","Dockerfile","README.md","infra/docker-compose.frontend.yml","app/api/public-forms/route.ts"].map(read).join("\n");
const legacyBrand=String.fromCharCode(98,114,101,101,114,111);
assert.ok(!repositoryText.toLowerCase().includes(legacyBrand),"legacy brand reference found");
assert.match(repositoryText,/BOOKED4SEASONS_API_BASE_URL/);
console.log(`PASS compliance routes=${routes.length} required_fields=15 leadconnector_widget=6a7ca95093aa928cd28c82f8`);
