export const metadata={title:"Privacy Policy",description:"Read how Booked4Seasons handles information submitted through the website and service-request process.",alternates:{canonical:"/privacy"}};

export default function Page(){return <section className="section"><div className="container legal">
  <p className="eyebrow">Effective August 13, 2026</p><h1>Privacy Policy</h1>
  <p>This Privacy Policy explains how Booked4Seasons.com handles information. Booked4Seasons is operated by <strong>Codestra LLC DBA Booked4Seasons</strong>, 20633 Longenbaugh Rd, Cypress, TX 77433.</p>
  <h2>Information you provide</h2><p>We may collect your name, email address, telephone number, service address, requested service, project description, scheduling preferences, contact preference, communications, and provider application information when you submit a form or contact us.</p>
  <h2>Information collected automatically</h2><p>Our hosting and security services may process IP address, browser and device information, referring page, pages viewed, timestamps, attribution information, and diagnostic or fraud-prevention logs.</p>
  <h2>How we use information</h2><ul><li>Receive, review, route, and respond to service requests and inquiries.</li><li>Coordinate requested services with appropriate independent providers.</li><li>Send scheduling, service, support, security, and—only with appropriate consent—promotional communications.</li><li>Operate, secure, troubleshoot, and improve the website.</li><li>Comply with legal, accounting, and dispute-resolution obligations.</li></ul>
  <h2>SMS privacy</h2><p>If you expressly opt in to text messages, we use your mobile number and consent record to send the message categories disclosed at opt-in. SMS consent is voluntary and is not a condition of purchase. Message frequency varies; message and data rates may apply. Reply STOP to opt out or HELP for help.</p><p><strong>We do not sell or share mobile numbers or SMS consent information with third parties or affiliates for their own marketing or promotional purposes.</strong> We may provide this information to messaging vendors acting for us solely to deliver and support Booked4Seasons messages, or where required by law.</p>
  <h2>Service providers and vendors</h2><p>Information reasonably necessary to respond to a request may be shared with independent service providers that may fulfill it and with vendors that host, secure, communicate, or process transactions for Booked4Seasons. They may use information only for the applicable service or as otherwise permitted by law.</p>
  <h2>Retention and security</h2><p>We retain information only as reasonably necessary for service coordination, support, security, accounting, disputes, and legal obligations, and use reasonable safeguards appropriate to the information.</p>
  <h2>Your choices</h2><p>You may opt out of promotional email using the link provided and opt out of SMS by replying STOP. Depending on applicable law, you may request access, correction, or deletion of certain information by contacting us.</p>
  <h2>Contact</h2><p><strong>Codestra LLC DBA Booked4Seasons</strong><br/>20633 Longenbaugh Rd<br/>Cypress, TX 77433<br/><a href="mailto:support@booked4seasons.com">support@booked4seasons.com</a><br/><a href="tel:+17543341625">+1 (754) 334-1625</a></p>
</div></section>}
