import Image from "next/image";
import Link from "next/link";
import { categories, services, servicesByCategory } from "@/lib/services";
import { ServiceCard } from "@/components/ServiceCard";

export const metadata={alternates:{canonical:"/"},openGraph:{title:"Booked4Seasons | Home services for every season",description:"Whatever your property needs, get it booked.",url:"/"}};
const popularSlugs=["hvac","plumbing","cleaning","electrical","lawn-care","junk-removal"];
const popular=popularSlugs.map(slug=>services.find(service=>service.slug===slug)!).filter(Boolean);

export default function Home(){return <>
  <section className="home-hero"><div className="container home-hero-grid"><div className="home-hero-copy"><p className="eyebrow">Home services for every season</p><h1>Whatever your property needs, <em>get it booked.</em></h1><p className="lead">Heating, cooling, cleaning, plumbing, landscaping, property maintenance, vehicle care and more—all in one place to request local service.</p><div className="hero-actions"><Link className="button" href="/request-service">Request service</Link><Link className="button button-secondary" href="/services">Explore services</Link></div><div className="trust-row"><span>No account required</span><span>17 services in one place</span><span>Local service coordination</span></div></div><div className="home-hero-image"><Image src="/images/home/homepage-hero.webp" alt="Service professional arriving at a cared-for modern suburban home" fill priority sizes="(max-width: 900px) 100vw, 55vw"/></div></div></section>
  <section className="service-finder"><div className="container service-finder-inner"><div><p className="eyebrow">What do you need help with?</p><h2>Start with a service.</h2></div><div className="service-finder-links">{popular.slice(0,5).map(service=><Link href={`/services/${service.slug}`} key={service.slug}>{service.name}<span>→</span></Link>)}<Link className="all-services-link" href="/services">All {services.length} services <span>→</span></Link></div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Popular services</p><h2>Get the everyday jobs moving.</h2></div><Link href="/services">View all services →</Link></div><div className="service-grid service-grid-three">{popular.map(service=><ServiceCard key={service.slug} service={service}/>)}</div></div></section>
  <section className="section section-dark"><div className="container"><div className="section-heading"><div><p className="eyebrow">How Booked4Seasons works</p><h2>A simpler path to local service.</h2></div><Link href="/how-it-works">See how it works →</Link></div><div className="steps"><div><span>1</span><h3>Tell us what you need</h3><p>Choose a service and describe the job.</p></div><div><span>2</span><h3>Share location and timing</h3><p>Add where and when service is preferred.</p></div><div><span>3</span><h3>We coordinate next steps</h3><p>Coverage and service details are confirmed with you.</p></div></div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Browse by category</p><h2>Care for more than one corner of life.</h2></div></div><div className="category-grid">{categories.map(category=><article key={category.name}><p className="eyebrow">{servicesByCategory[category.name].length} services</p><h3>{category.name}</h3><p>{category.description}</p><Link href={`/services#${category.name.toLowerCase().replaceAll(" ","-").replace("&-","")}`}>Explore category →</Link></article>)}</div></div></section>
  <section className="section section-soft"><div className="container image-split"><div className="section-image"><Image src="/images/home/why-booked4seasons.webp" alt="Homeowner reviewing service details with a local service professional" fill sizes="(max-width: 900px) 100vw, 50vw"/></div><div><p className="eyebrow">Why Booked4Seasons</p><h2>One recognizable place to begin.</h2><p className="lead">Property needs change. The place you start does not have to.</p><div className="stacked-benefits"><div><strong>Multiple services, one place</strong><p>Home systems, property care, specialty work, and mobile vehicle service.</p></div><div><strong>A clear request process</strong><p>Share the details once, without creating an account.</p></div><div><strong>Support for the next step</strong><p>We help coordinate based on service type and local coverage.</p></div></div></div></div></section>
  <section className="section"><div className="container image-split reverse"><div><p className="eyebrow">Seasonal service</p><h2>Your property never has just one season.</h2><p className="lead">Cooling in summer, heating in winter, cleanups in between—and the unexpected jobs that never check the calendar.</p><Link className="button button-secondary" href="/services">Find a service</Link></div><div className="section-image"><Image src="/images/home/seasonal-services.webp" alt="Cared-for home and yard receiving seasonal property service" fill sizes="(max-width: 900px) 100vw, 50vw"/></div></div></section>
  <section className="section section-dark"><div className="container trust-band"><div><p className="eyebrow">Simple by design</p><h2>Clarity before claims.</h2></div><div className="trust-points"><p>Coverage is confirmed by service and location.</p><p>No invented guarantees or unverified ratings.</p><p>Customer support is part of the experience.</p></div></div></section>
  <section className="section section-soft"><div className="container dual-cta"><article><p className="eyebrow">Service areas</p><h2>See whether we can help where you are.</h2><p>Availability varies by service and ZIP code.</p><Link href="/service-areas">Check service areas →</Link></article><article><p className="eyebrow">For professionals</p><h2>Build the network with us.</h2><p>Tell us about your company, services, and coverage.</p><Link href="/become-a-pro">Become a Pro →</Link></article></div></section>
  <section className="section"><div className="container split"><div><p className="eyebrow">Common questions</p><h2>Know what to expect before you request.</h2><p className="lead">Straightforward answers about service requests, availability, and next steps.</p><Link className="button button-secondary" href="/faq">View all FAQs</Link></div><div className="faq-list"><details><summary>Do I need an account?</summary><p>No. You can submit an initial request without creating an account.</p></details><details><summary>How is availability confirmed?</summary><p>Availability depends on the requested service and location. We confirm the appropriate next step after reviewing those details.</p></details><details><summary>Does a request guarantee service?</summary><p>No. A request begins the coordination process; service details and coverage still need confirmation.</p></details></div></div></section>
  <section className="section"><div className="container cta"><div><p className="eyebrow">Ready when you are</p><h2>What needs to get done?</h2><p className="lead">Start a simple request and tell us the basics.</p></div><Link className="button" href="/request-service">Request service</Link></div></section>
</>}
